### ISSUE TITLE
NoneType error messages when some trackers being submitted

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#175]
see: 

Traceback (most recent call last):

  File "/home/www/env/lib/python2.7/site-packages/tastypie/resources.py", line 195, in wrapper
    response = callback(request, *args, **kwargs)

  File "/home/www/env/lib/python2.7/site-packages/tastypie/resources.py", line 426, in dispatch_list
    return self.dispatch('list', request, **kwargs)

  File "/home/www/env/lib/python2.7/site-packages/tastypie/resources.py", line 458, in dispatch
    response = method(request, **kwargs)

  File "/home/www/env/lib/python2.7/site-packages/oppia/api/resources.py", line 381, in patch_list
    self.obj_create(bundle, request=request)

  File "/home/www/env/lib/python2.7/site-packages/tastypie/resources.py", line 2084, in obj_create
    return self.save(bundle)

  File "/home/www/env/lib/python2.7/site-packages/tastypie/resources.py", line 2230, in save
    bundle.obj.save()

  File "/home/www/env/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)

  File "/home/www/env/lib/python2.7/site-packages/django/db/models/base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)

  File "/home/www/env/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)

  File "/home/www/env/lib/python2.7/site-packages/oppia/signals.py", line 147, in tracker_callback
    if tracker.course.user == tracker.user and settings.OPPIA_COURSE_OWNERS_EARN_POINTS is False:

AttributeError: 'NoneType' object has no attribute 'user'

**Comment by alexlittle** [comment]
No longer getting this error - so closing
