### ISSUE TITLE
Fix issue where activities may not have descriptions entered

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#207]
So should be optional on upload, see:

Traceback (most recent call last):

  File "/home/nurhi/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/nurhi/django-nurhi-oppia/oppia/views.py", line 147, in upload
    course = handle_uploaded_file(request.FILES['course_file'], extract_path, request, is_draft)

  File "/home/nurhi/django-nurhi-oppia/oppia/uploader.py", line 141, in handle_uploaded_file
    activity_create(section, a,False)

  File "/home/nurhi/django-nurhi-oppia/oppia/uploader.py", line 210, in activity_create
    description[t.getAttribute('lang')] = d.firstChild.nodeValue

AttributeError: 'NoneType' object has no attribute 'nodeValue'

This is as a result of a resource activity not having a proper description

**Comment by alexlittle** [comment]
This can be recreated by:

- in Moodle course create a new activity - using the Moodle 'file' activity type
- Add a title and a resource file, but don't add a description
- export the course package in moodle, the course will export fine and you can download the zip
- however when uploading as there is no description it fails when uploading to Oppia server

Likely just need to make the description optional for this activity type
