### ISSUE TITLE
Error in video embed helper (list index out of range)

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#283]
Internal Server Error: /content/video-embed-helper/
Traceback (most recent call last):
  File "/xxxxxxxxxxxxxxxxxxx/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/xxxxxxxxxxxxxxxxxxx/oppia/content/views.py", line 45, in video_embed_helper
    file_length = get_length(video_local_file)
  File "/xxxxxxxxxxxxxxx/oppia/content/views.py", line 91, in get_length
    time_components = duration_list[0].split(',')[0].split(':')
IndexError: list index out of range

Request repr(): 
<WSGIRequest
path:/content/video-embed-helper/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'csrfmiddlewaretoken': [u'xxxxxxxxxxxxxxxxxx'], u'submit': [u'Go'], u'video_url': [u'http://moodle.jhpiego.org/media/PAC/1-2.mp4']}>,

**Comment by alexlittle** [comment]
Another error when not using http:

Internal Server Error: /content/video-embed-helper/
Traceback (most recent call last):
  File "/xxxxxxxxxxxxxxxx/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/xxxxxxxxxxxxxxxxx/django-oppia/oppia/content/views.py", line 39, in video_embed_helper
    urllib.urlretrieve(video_url, filename=video_local_file)
  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 205, in open
    return self.open_unknown(fullurl, data)
  File "/usr/lib/python2.7/urllib.py", line 217, in open_unknown
    raise IOError, ('url error', 'unknown url type', type)
IOError: [Errno url error] unknown url type: 'sftp'

Request repr(): 
<WSGIRequest
path:/content/video-embed-helper/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'csrfmiddlewaretoken': [u''], u'submit': [u'Go'], u'video_url': [u'sftp://ftpmoodle@moodle.http://xxxxxxxxxxxxxxx/media/ENC/Page19-20_a.mp4']}>,
