### ISSUE TITLE
Points/gamification not working on staging server with python 3/django 2

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#635]
Get a basic input/output error when trying to save the updated points on the staging server, but not on local dev server.

Stack trace:

Traceback:

File "/home/oppia-staging/env/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/home/oppia-staging/env/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)

File "/home/oppia-staging/env/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/oppia-staging/django-oppia/gamification/views.py" in edit_course_gamification
  158.                 new_version = writer.update_gamification(request.user)

File "/home/oppia-staging/django-oppia/gamification/xml_writer.py" in update_gamification
  145.         print('parsing course XML')

Exception Type: OSError at /gamification/points/course/40/
Exception Value: [Errno 5] Input/output error

**Comment by alexlittle** [comment]
Potentially related to this: https://stackoverflow.com/questions/10409897/ioerror-input-output-error-when-printing
Maybe because it's running under the python manage.py runserver command as a background process?

**Comment by alexlittle** [comment]
When having runserver running in the foreground at the server terminal, I no longer get this specific message. But there is now a different error...

parsing course XML
/home/oppia-staging/oppia-uploads/anc1-rg-20150611094312.zip
Updating gamification XML nodes...
course_downloaded
Writing new course XML contents...
Internal Server Error: /gamification/points/course/39/
Traceback (most recent call last):
  File "/home/oppia-staging/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/oppia-staging/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/oppia-staging/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/oppia-staging/django-oppia/gamification/views.py", line 158, in edit_course_gamification
    new_version = writer.update_gamification(request.user)
  File "/home/oppia-staging/django-oppia/gamification/xml_writer.py", line 155, in update_gamification
    courseFile.rewrite_xml_contents(user, self.course, self.xml)
  File "/home/oppia-staging/django-oppia/oppia/utils/courseFile.py", line 32, in rewrite_xml_contents
    remove_from_zip(course_zip_file, temp_zip_path, course.shortname, module_xml)
  File "/home/oppia-staging/django-oppia/oppia/utils/courseFile.py", line 18, in remove_from_zip
    shutil.copy(tempname, zipfname)
  File "/home/oppia-staging/env/lib/python3.6/shutil.py", line 246, in copy
    copymode(src, dst, follow_symlinks=follow_symlinks)
  File "/home/oppia-staging/env/lib/python3.6/shutil.py", line 144, in copymode
    chmod_func(dst, stat.S_IMODE(st.st_mode))
PermissionError: [Errno 1] Operation not permitted: '/home/oppia-staging/oppia-uploads/anc1-rg-20150611094312.zip'

**Comment by jjoseba** [comment]
The first one was surely linked with launching the process in the terminal as a background process. When the terminal session ends, the `stdout` for that process no longer exists, causing the `print()` command to break. 

The second one seems like a permissions issue... with which user are you running the process? As I see in the staging server, the current version of the file is owned by the user `www-data`. I see that the `shutil.copy()` function also copies the file permission bits (in fact, the function raising the error is a `chmod`. Using `shutil.copyfile()` should solve the issue... al open a PR with that change.
