### ISSUE TITLE
Deprecation warning for BaseException.message

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#636]
django-oppia/oppia/uploader.py:49: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  messages.error(request, e.message, extra_tags="danger")

**Comment by alexlittle** [comment]
Potentially related... when running the tests I get the following error:

ERROR: test_upload_permission_staff (tests.api.test_course_publish.CoursePublishResourceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/data/Digital-Campus/development/core/django-oppia/tests/api/test_course_publish.py", line 77, in test_upload_permission_staff
    response = self.client.post(self.url, { 'username': 'staff', 'password': 'password', 'tags': 'demo', 'is_draft': False, api.COURSE_FILE_FIELD: course_file })
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/test/client.py", line 535, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/test/client.py", line 349, in post
    secure=secure, **extra)
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/test/client.py", line 414, in generic
    return self.request(**r)
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/test/client.py", line 495, in request
    raise exc_value
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/alex/data/Digital-Campus/development/core/django-oppia/api/publish.py", line 114, in publish_view
    return JsonResponse(response_data, status=status)
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ExpatError' is not JSON serializable

**Comment by jjoseba** [comment]
Was resolved on commit 4bf4f5da6260552afccfa6afdbe4bde2369ffdf2
