### ISSUE TITLE
Fix tests for v0.12.0 branch

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#638]
Several tests are failing with python 3 django 2

**Comment by alexlittle** [comment]
I'm still getting a couple of errors/failures with the tests....

ERROR: test_upload_template (tests.av.test_media_upload.MediaUploadResourceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/data/Digital-Campus/development/core/django-oppia/tests/av/test_media_upload.py", line 34, in test_upload_template
    response = self.client.post(reverse('oppia_av_upload'), {'media_file': media_file })
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/test/client.py", line 535, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/test/client.py", line 349, in post
    secure=secure, **extra)
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/test/client.py", line 414, in generic
    return self.request(**r)
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/test/client.py", line 495, in request
    raise exc_value
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alex/data/Digital-Campus/development/core/oppia_p3d2/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alex/data/Digital-Campus/development/core/django-oppia/av/views.py", line 45, in upload_view
    result = handler.upload(request, request.user)
  File "/home/alex/data/Digital-Campus/development/core/django-oppia/av/handler.py", line 31, in upload
    media_length = get_length(media_full_path)
  File "/home/alex/data/Digital-Campus/development/core/django-oppia/av/handler.py", line 54, in get_length
    duration_list = [x for x in result.stdout.readlines() if "Duration" in x]
  File "/home/alex/data/Digital-Campus/development/core/django-oppia/av/handler.py", line 54, in <listcomp>
    duration_list = [x for x in result.stdout.readlines() if "Duration" in x]
TypeError: a bytes-like object is required, not 'str'

======================================================================
FAIL: test_quiz_attempt_points_included (tests.quiz.test_quiz_attempt_offline.QuizAttemptResourceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/data/Digital-Campus/development/core/django-oppia/tests/quiz/test_quiz_attempt_offline.py", line 110, in test_quiz_attempt_points_included
    self.assertEqual(points_count_start, points_count_end)
AssertionError: 1 != 3

----------------------------------------------------------------------
Ran 271 tests in 194.773s

FAILED (failures=1, errors=1)
