### ISSUE TITLE
tests.av.models.test_media_embed_code fails on LMH but not core

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/django-oppia#719]
error message:

ERROR: test_media_embed_code (tests.av.models.test_media_embed_code.MediaEmbedCodeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/data/Digital-Campus/development/lastmilehealth/django-oppia/tests/av/models/test_media_embed_code.py", line 22, in test_media_embed_code
    supplied_embed_code = re.sub(' +' , ' ', embed_code)
  File "/home/alex/data/Digital-Campus/development/lastmilehealth/lmh/env_p3/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

**Comment by alexlittle** [comment]
transferred to LMH issue list: https://github.com/LMHOppia/django-oppia/issues/13
